sudo: false

language: php

php:
- "7.2"
- "7.3"

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
- composer install

script:
- >
  echo;
  echo "Validating the composer.json";
  composer validate --no-check-all --no-check-lock --strict;

- >
  echo;
  echo "Linting all PHP files";
  composer ci:php:lint;

- >
  echo;
  echo "Running the unit tests";
  composer ci:tests:unit;

- >
  echo;
  echo "Running the integration tests";
  composer ci:tests:integration;
