---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
      - name: "Run PHP lint"
        run: "composer ci:php:lint"

  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    needs: php-lint
    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}
               -composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.composer/cache
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install composer dependencies"
        run: |
          composer install --no-ansi --no-interaction --no-progress
          composer show
      - name: "Run tests"
        run: "composer ci:tests:unit"

  functional-tests:
    name: "Functional tests"
    runs-on: ubuntu-latest
    needs: php-lint
    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}
               -composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.composer/cache
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install composer dependencies"
        run: |
          composer install --no-ansi --no-interaction --no-progress
          composer show
      - name: "Run tests"
        run: "composer ci:tests:functional"
